### ISSUE TITLE
Doesn't seem to save or use URL

### ISSUE THREAD

**Issue by ajft** [dotMR/CamliClipper#7]
I'm using Version Chrome on a Ubuntu 15.04 system (Chrome 43.0.2357.81 unknown (64-bit)).  I've loaded the extension, then in the options I've tried a few variations of the strings "http://localhost:3179" and "http://localhost:3179/" along with "#clipped" in the tags field.  When I press "Save" I'm told "Options Saved!" but when I try and clip and images I'm always told "Server not available" and if I re-enter the options dialog, the "server URL" field is empty while the "tags" field shows my previous entry.

camlistored is up to date today (2015-06-03) from git:
$ ./bin/camlistored -version
camlistored version: unknown
Go version: go1.4.2 (linux/amd64)

**Comment by dotMR** [comment]
Thanks for the report. Can you check the browser JS console and see if anything else is printed?

I should be able todo some local testing later today to see if it is something obvious (I actually didn't think anyone else was using it yet, so maybe I just checked in some bad code and hadn't encountered it yet).

**Comment by ajft** [comment]
No, there's nothing appears in the JS console.

**Comment by dotMR** [comment]
Try it out now. There was an issue with the name of the server url parameter being persisted to storage.

Please let me know if you have any further problems or suggestions.

**Comment by ajft** [comment]
Mario,

Yes, all working now.

thank you,
  Adrian

On Wed, Jun 3, 2015 at 9:25 PM, Mario Russo notifications@github.com
wrote:

> Try it out now. There was an issue with the name of the server url
> parameter being persisted to storage.
> 
> Please let me know if you have any further problems or suggestions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dotMR/CamliClipper/issues/7#issuecomment-108312699.

## 

Adrian Tritschler
Melbourne, Australia
